### ISSUE TITLE
Create enable/disable triggers for groups of required plugins across all devops actions

### ISSUE THREAD

**Issue by richorrichard** [joshcummingsdesign/grizzly-wp#162]
Essentially need to make it fairly straightforward to set which plugins are enabled/disabled on various pushes/pulls/deploys. examples: 

**Disable during `make clone-staging`**
* ElasticPress

**Enable on `make deploy-prod`**
* W3 Total Cache
* ElasticPress
* etc

**Comment by joshcummingsdesign** [comment]
W3 Total Cache has been resolved in d8e197f

**Comment by joshcummingsdesign** [comment]
ElasticPress should be the same across all environments. See #140
