### ISSUE TITLE
Mysqldump error for 'make clone-staging'

### ISSUE THREAD

**Issue by richorrichard** [joshcummingsdesign/grizzly-wp#46]
error could be related to the .env file's declaration of db username and password?

```
Preparing the database...
mysqldump: Got error: 1045: "Access denied for user 'admin'@'98.176.203.20' (using password: YES)" when trying to connect
Importing the database...
```

**Comment by joshcummingsdesign** [comment]
Working ok on my end. Try after a fresh pull with gzclone. If that doesn't work, let's touch base on monday.

**Comment by joshcummingsdesign** [comment]
Confirmed resolved with fresh gzclone.
