### ISSUE TITLE
Caching In Pattern Lab

### ISSUE THREAD

**Issue by brettmarshall** [joshcummingsdesign/grizzly-wp#83]
When you create a new pattern ( atom, molecule, etc. ) It will take about 5 minutes to show.

**Comment by joshcummingsdesign** [comment]
Saving another mustache file and coming back and refreshing seems to fix this. Wonder if it's a caching issue.

**Comment by joshcummingsdesign** [comment]
Doesn't seem to be a caching issue as stopping gulp watch and running gulp && gulp watch fixes this. Need to look at Browsersync watch tasks.

**Comment by joshcummingsdesign** [comment]
Need to look into Browsersync, but for now, just save another file and it should refresh properly.

**Comment by joshcummingsdesign** [comment]
Fixed in 2.0.1-beta

**Comment by joshcummingsdesign** [comment]
Resolved by refactoring gulpfile.
