### ISSUE TITLE
Add clarification about how `make clone-staging` should be used

### ISSUE THREAD

**Issue by richorrichard** [joshcummingsdesign/grizzly-wp#90]
`make clone-staging` should be used only on the `staging` branch; the idea here is that, since it overwrites your local with what's on staging, it should only reflect that branch. I'd love to see a dialog added that verifies that you're on the correct branch. For NTNX and NUVA that branch is `staging` but should eventually be turned into the `develop` branch.

**Comment by joshcummingsdesign** [comment]
Good call. Short term, let's add the dialog and a note in the docs. Prior to the 1.0 release, let's nail down the branch naming and get it documented properly.

**Comment by joshcummingsdesign** [comment]
See #66

**Comment by joshcummingsdesign** [comment]
e1a94fb Adds validation to check for staging branch.
