### ISSUE TITLE
Docker setup negates IDE code reference functionality

### ISSUE THREAD

**Issue by richorrichard** [joshcummingsdesign/grizzly-wp#92]
Because wp-admin isn't included in the build the goto declaration functionality is broken and the markup registers WP functions as missing declarations. May want to look into ways around this issue – potentially with configuring reference symlinks to the actual docker instance's wp-admin or something.. or including that directory as external library or something.

**Comment by joshcummingsdesign** [comment]
More volumes = more overhead. Something that needs to be considered carefully. Is this something that is absolutely required?

**Comment by joshcummingsdesign** [comment]
Also, the point is to abstract WordPress, because you shouldn't ever need to change core files.

**Comment by joshcummingsdesign** [comment]
See #79

**Comment by joshcummingsdesign** [comment]
Is there a way to turn this off in your IDE, or ignore core folders?

**Comment by joshcummingsdesign** [comment]
This is being resolved in 5.0.0-beta.
