### ISSUE TITLE
Sourcemaps not working over SSL

### ISSUE THREAD

**Issue by joshcummingsdesign** [joshcummingsdesign/grizzly-wp#98]
See BrowserSync/browser-sync#639

**Comment by joshcummingsdesign** [comment]
Looks to be an issue with Chrome loading sourcemaps when using BrowserSync to proxy a server with a self-signed SSL certificate.

**Comment by joshcummingsdesign** [comment]
Switching to inline sourcemaps resolved the issue. Working on a PR for this.

**Comment by joshcummingsdesign** [comment]
Fixed in 3a205e3

**Comment by valgussev** [comment]
Having the same issue on Chrome v60 on OS X 10.11. Source maps are loaded from time to time using browser-sync proxy. There is no such a problem on a webserver itself and on Firefox. My connection is over SSL. Setting source maps to use sourcesContent doesn't fix the issue.
